# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.cache/wt [current_project]
set_property parent.project_path D:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-z7-20:part0:1.1 [current_project]
set_property ip_output_repo d:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.srcs/sources_1/new/Effect_1.v
  D:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.srcs/sources_1/new/Effect_2.v
  D:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.srcs/sources_1/new/Effect_3.v
  D:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.srcs/sources_1/new/Effect_4.v
  D:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.srcs/sources_1/new/Effect_5.v
  D:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.srcs/sources_1/new/effectMode.v
  D:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.srcs/sources_1/new/frequency.v
  D:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.srcs/sources_1/new/timer.v
  D:/BKU/HK241/Logic_Design_Project/Draft/Effect_Led_Project/Draft.srcs/sources_1/new/EffectLed.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/baobu/Downloads/digilent-xdc-master/digilent-xdc-master/Arty-Z7-20-Master.xdc
set_property used_in_implementation false [get_files C:/Users/baobu/Downloads/digilent-xdc-master/digilent-xdc-master/Arty-Z7-20-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top EffectLed -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef EffectLed.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file EffectLed_utilization_synth.rpt -pb EffectLed_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
